/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ProductController;
import Model.Product;
import java.awt.HeadlessException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Logger;

/**
 *
 * @author MY PC
 */
public class ProductView extends javax.swing.JFrame {
 
    private static final Logger logger = Logger.getLogger(ProductView.class.getName());

 private final ProductController controller = new ProductController();

    /**
     * Creates new form ProductView
     */
    public ProductView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        product_lbl = new javax.swing.JLabel();
        Pname_lbl = new javax.swing.JLabel();
        price_lbl = new javax.swing.JLabel();
        quantity_lbl = new javax.swing.JLabel();
        productid_fld = new javax.swing.JTextField();
        price_fld = new javax.swing.JTextField();
        Pname_fld = new javax.swing.JTextField();
        quantity_fld = new javax.swing.JTextField();
        add_btn = new javax.swing.JButton();
        clear_btn = new javax.swing.JButton();
        search_fld = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        view_tbl = new javax.swing.JTable();
        search_btn = new javax.swing.JButton();
        view_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("PRODUCTS");

        product_lbl.setText("Product ID");

        Pname_lbl.setText("Product Name");

        price_lbl.setText("Price");

        quantity_lbl.setText("Quantity");

        productid_fld.addActionListener(this::productid_fldActionPerformed);

        price_fld.addActionListener(this::price_fldActionPerformed);

        Pname_fld.addActionListener(this::Pname_fldActionPerformed);

        quantity_fld.addActionListener(this::quantity_fldActionPerformed);

        add_btn.setText("Add");
        add_btn.addActionListener(this::add_btnActionPerformed);

        clear_btn.setText("Clear");
        clear_btn.addActionListener(this::clear_btnActionPerformed);

        search_fld.setText("Search Hear");
        search_fld.addActionListener(this::search_fldActionPerformed);

        view_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product ID", "Product Name", "Price", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(view_tbl);

        search_btn.setText("Search");
        search_btn.addActionListener(this::search_btnActionPerformed);

        view_btn.setText("View All");
        view_btn.addActionListener(this::view_btnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(search_fld, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(search_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(view_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(product_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(price_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(price_fld, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                    .addComponent(productid_fld))
                                .addGap(79, 79, 79)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Pname_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Pname_fld, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(quantity_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(quantity_fld, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(add_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(clear_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pname_lbl)
                    .addComponent(product_lbl)
                    .addComponent(productid_fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pname_fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price_lbl)
                    .addComponent(price_fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantity_lbl)
                    .addComponent(quantity_fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_btn)
                    .addComponent(clear_btn))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(view_btn)
                    .addComponent(search_btn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productid_fldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productid_fldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productid_fldActionPerformed

    private void Pname_fldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pname_fldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pname_fldActionPerformed

    private void price_fldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_price_fldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_price_fldActionPerformed

    private void quantity_fldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantity_fldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantity_fldActionPerformed

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        // TODO add your handling code here:
        
                try {
            String id = productid_fld.getText().trim();
            String name = Pname_fld.getText().trim();
            double price = Double.parseDouble(price_fld.getText());
            int qty = Integer.parseInt(quantity_fld.getText());
            
            if (id.isEmpty() || name.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Fill all fields!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Product p = new Product(id, name, price, qty);

            boolean success = controller.addProduct(p);

            if (success) {
                JOptionPane.showMessageDialog(this, "Product Added Successfully!");
                clearFields();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to Add Product!", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid Input: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
      
        
    }//GEN-LAST:event_add_btnActionPerformed

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
        // TODO add your handling code here:
       clearFields();
    }

    private void clearFields() {
        productid_fld.setText("");
        Pname_fld.setText("");
        price_fld.setText("");
        quantity_fld.setText("");
        
        search_fld.setText("");
    
    }//GEN-LAST:event_clear_btnActionPerformed

    private void search_fldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_fldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_fldActionPerformed

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        // TODO add your handling code here:
        
         String id = search_fld.getText().trim();
        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter Product ID to Search!");
            return;
        }

        Product p = controller.searchProduct(id);

        if (p != null) {
            DefaultTableModel model = (DefaultTableModel) view_tbl.getModel();
            model.setRowCount(0); // clear table

            model.addRow(new Object[]{
                p.getProductId(),
                p.getProductName(),
                p.getPrice(),
                p.getQuantity(),
                
            });
        } else {
            JOptionPane.showMessageDialog(this, "Product Not Found!");
        }
                           
        
    }//GEN-LAST:event_search_btnActionPerformed

    private void view_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_btnActionPerformed
        // TODO add your handling code here:
    
      ArrayList<Product> list = controller.getAllProducts();

    DefaultTableModel model = (DefaultTableModel) view_tbl.getModel();
    model.setRowCount(0);

    for (Product p : list) {
        model.addRow(new Object[]{
            p.getProductId(),
            p.getProductName(),
            p.getPrice(),
            p.getQuantity(),
           
        });
    }
                                           
    }//GEN-LAST:event_view_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ProductView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Pname_fld;
    private javax.swing.JLabel Pname_lbl;
    private javax.swing.JButton add_btn;
    private javax.swing.JButton clear_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField price_fld;
    private javax.swing.JLabel price_lbl;
    private javax.swing.JLabel product_lbl;
    private javax.swing.JTextField productid_fld;
    private javax.swing.JTextField quantity_fld;
    private javax.swing.JLabel quantity_lbl;
    private javax.swing.JButton search_btn;
    private javax.swing.JTextField search_fld;
    private javax.swing.JButton view_btn;
    private javax.swing.JTable view_tbl;
    // End of variables declaration//GEN-END:variables
}
